name: Sync Airbnb Calendars

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
  
  # This schedules the workflow to run automatically
  schedule:
    # Runs every 4 hours. You can change the schedule using cron syntax.
    - cron: '0 */4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # This step creates the credentials.json file using a reliable Python command
      - name: Create credentials.json from secret
        env:
          CREDENTIALS_JSON_DATA: ${{ secrets.CREDENTIALS_JSON }}
        shell: python
        run: |
          import os
          secret_data = os.environ['CREDENTIALS_JSON_DATA']
          with open('credentials.json', 'w') as f:
              f.write(secret_data)

      # This step creates the token.json file using a reliable Python command
      - name: Create token.json from secret
        env:
          TOKEN_JSON_DATA: ${{ secrets.TOKEN_JSON }}
        shell: python
        run: |
          import os
          secret_data = os.environ['TOKEN_JSON_DATA']
          with open('token.json', 'w') as f:
              f.write(secret_data)

      - name: Run the sync script
        # This step passes the other secrets directly to the script as environment
        # variables, which is safer than using a .env file in this context.
        env:
          TARGET_CALENDAR_ID: ${{ secrets.TARGET_CALENDAR_ID }}
          ICAL_CONFIG_JSON: ${{ secrets.ICAL_CONFIG_JSON }}
        # Make sure this filename matches the one in your repository
        run: python main.py
